// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/ipanardian/price-api/internal/service"
)

// Injectors from injector.go:

func InitializeHermesService() (service.HermesService, error) {
	hermesService := service.NewHermesService()
	return hermesService, nil
}

